In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_df = pd.read_csv("data/movies.csv")
movie_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy


In [3]:
movie_df.isna().any()

movieId    False
title      False
genres     False
dtype: bool

In [4]:
movie_df.duplicated().any()

False

In [5]:
movie_df.dtypes

movieId     int64
title      object
genres     object
dtype: object

In [6]:
genres = movie_df['genres'].head()

In [7]:
genres_split = movie_df['genres'].str.get_dummies(sep='|')
genres_split

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9737,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9738,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9739,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
9740,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


In [8]:
movie = pd.concat([movie_df['movieId'], genres_split])
movie

,movieId,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9737,NaN,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9738,NaN,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9739,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9740,NaN,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [9]:
movie.fillna(movie.fillna(0))
movies = movie.fillna(0)
movies

,movieId,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9737,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9738,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9740,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [10]:
movies.isna().sum()

movieId               0
(no genres listed)    0
Action                0
Adventure             0
Animation             0
Children              0
Comedy                0
Crime                 0
Documentary           0
Drama                 0
Fantasy               0
Film-Noir             0
Horror                0
IMAX                  0
Musical               0
Mystery               0
Romance               0
Sci-Fi                0
Thriller              0
War                   0
Western               0
dtype: int64

In [11]:
ratings_df = pd.read_csv("data/ratings.csv")
ratings_df.head()

,userId,movieId,rating,timestamp
0,1,1,4.0,964982703
1,1,3,4.0,964981247
2,1,6,4.0,964982224
3,1,47,5.0,964983815
4,1,50,5.0,964982931


In [12]:
ratings_df.isna().any()

userId       False
movieId      False
rating       False
timestamp    False
dtype: bool

In [13]:
ratings_df.duplicated().any()

False

In [14]:
ratings_df.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [15]:
ratings_df["rating"].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [16]:
ratings_df['userId'].value_counts().tail()

userId
442    20
569    20
320    20
576    20
53     20
Name: count, dtype: int64

In [17]:
ratings_df['userId'].nunique()

610

In [18]:
ratings_df[ratings_df['userId'] == 610]

,userId,movieId,rating,timestamp
99534,610,1,5.0,1479542900
99535,610,6,5.0,1493850345
99536,610,16,4.5,1479542171
99537,610,32,4.5,1479543331
99538,610,47,5.0,1479545853
...,...,...,...,...
100831,610,166534,4.0,1493848402
100832,610,168248,5.0,1493850091
100833,610,168250,5.0,1494273047
100834,610,168252,5.0,1493846352


In [19]:
ratings = ratings_df.pivot(index = 'userId', columns='movieId', values = 'rating')
ratings.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [38]:
ratings = ratings.fillna(0)
ratings

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [21]:
ratings.isna().any()

movieId
1         False
2         False
3         False
4         False
5         False
          ...  
193581    False
193583    False
193585    False
193587    False
193609    False
Length: 9724, dtype: bool

In [22]:
tags_df = pd.read_csv("data/tags.csv")
tags_df.head()

,userId,movieId,tag,timestamp
0,2,60756,funny,1445714994
1,2,60756,Highly quotable,1445714996
2,2,60756,will ferrell,1445714992
3,2,89774,Boxing story,1445715207
4,2,89774,MMA,1445715200


In [23]:
tags_df.isna().any()

userId       False
movieId      False
tag          False
timestamp    False
dtype: bool

In [24]:
tags_df.duplicated().any()

False

In [25]:
tags_df.dtypes

userId        int64
movieId       int64
tag          object
timestamp     int64
dtype: object

In [26]:
movie_arr = movies.to_numpy()
ratings_arr = ratings.to_numpy()

In [27]:
print(movie_arr)

[[1. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
print(ratings_arr)

[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]


In [29]:
ratings.shape

(610, 9724)

In [30]:
from numpy.linalg import norm
def cosine_similarity_movie(matrix):
    norms = norm(matrix, axis = 0)
    """ axis = 0 is walking down each column
        norm is taking the sqrt of the sum of the square with each item in the column"""
    norms[norms == 0] = 1e-10
    # use 1e-10 = 0.0000000001 replace 0 to make sure the data is worked
    normalised = matrix/norms
    similarity_matrix = np.dot(normalised.T, normalised)
    # (n-movie * n-users) @ (n-users * n-movie) = (n-movie * n-movie)
    return similarity_matrix

In [31]:
def cosine_similarity_user(matrix):
    norms = norm(matrix, axis = 1)
    norms[norms == 0] = 1e-10
    normalised = matrix/norms[:, np.newaxis]
    # comparing to the users, not the movie.
    similarity_matrix = np.dot(normalised, normalised.T)
    return similarity_matrix

In [32]:
import numpy as np
import ipytest

ipytest.autoconfig()

def similarity_matrix_diag_check(similarity_matrix):
    assert np.allclose(np.diag(similarity_matrix), 1.0) == True

def similarity_matrix_shape_check(sim_matrix, matrix):
    assert sim_matrix.shape == (matrix.shape[1], matrix.shape[1])

def user_similarity_matrix_shape_check(sim_matrix_user, ratings_arr):
    assert sim_matrix_user.shape == (ratings_arr.shape[0],ratings_arr.shape[0])

def similarity_matrix_allclose_check(similarity_matrix):
    assert np.allclose(similarity_matrix, similarity_matrix.T) == True

def test_similarity_matrix_item():
    global sim_matrix
    sim_matrix = cosine_similarity_movie(ratings_arr)
    similarity_matrix_diag_check(sim_matrix)
    similarity_matrix_shape_check(sim_matrix, ratings_arr)
    similarity_matrix_allclose_check(sim_matrix)


def test_similarity_matrix_user():
    global sim_matrix_user
    sim_matrix_user = cosine_similarity_user(ratings_arr)
    similarity_matrix_diag_check(sim_matrix_user)
    user_similarity_matrix_shape_check(sim_matrix_user, ratings_arr)
    similarity_matrix_allclose_check(sim_matrix_user)

ipytest.autoconfig(addopts=["--color=yes"])
ipytest.run("-v")

======================================= test session starts ========================================
platform darwin -- Python 3.12.2, pytest-7.4.4, pluggy-1.0.0 -- /opt/anaconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/hercules/projects/camellia
plugins: anyio-4.2.0, typeguard-4.3.0
collecting ... collected 2 items

t_6f092d9679344c1c8294cbecbbaf34db.py::test_similarity_matrix_item PASSED                    [ 50%]
t_6f092d9679344c1c8294cbecbbaf34db.py::test_similarity_matrix_user PASSED                    [100%]

======================================== 2 passed in 3.80s =========================================


<ExitCode.OK: 0>

In [33]:
print(sim_matrix)

[[1.         0.41056206 0.2969169  ... 0.         0.         0.        ]
 [0.41056206 1.         0.28243799 ... 0.         0.         0.        ]
 [0.2969169  0.28243799 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [34]:
print(sim_matrix_user)

[[1.         0.02728287 0.05972026 ... 0.29109737 0.09357193 0.14532081]
 [0.02728287 1.         0.         ... 0.04621095 0.0275654  0.10242675]
 [0.05972026 0.         1.         ... 0.02112846 0.         0.03211875]
 ...
 [0.29109737 0.04621095 0.02112846 ... 1.         0.12199271 0.32205486]
 [0.09357193 0.0275654  0.         ... 0.12199271 1.         0.05322546]
 [0.14532081 0.10242675 0.03211875 ... 0.32205486 0.05322546 1.        ]]


In [55]:
ratings_mean = ratings.mean()
print(ratings_mean, end="\n")

user_means = ratings.mean(axis=1) 
print(user_means)

movieId
1         1.381967
2         0.618852
3         0.277869
4         0.027049
5         0.246721
            ...   
193581    0.006557
193583    0.005738
193585    0.005738
193587    0.005738
193609    0.006557
Length: 9724, dtype: float64
userId
1      0.104175
2      0.011775
3      0.009770
4      0.078980
5      0.016454
         ...   
606    0.419375
607    0.072810
608    0.267842
609    0.012443
610    0.493881
Length: 610, dtype: float64


In [46]:
centered = ratings.sub(ratings_mean, axis = 1)
ratings_centered = centered.to_numpy()
ratings_centered

array([[ 2.61803279, -0.61885246,  3.72213115, ..., -0.0057377 ,
        -0.0057377 , -0.00655738],
       [-1.38196721, -0.61885246, -0.27786885, ..., -0.0057377 ,
        -0.0057377 , -0.00655738],
       [-1.38196721, -0.61885246, -0.27786885, ..., -0.0057377 ,
        -0.0057377 , -0.00655738],
       ...,
       [ 1.11803279,  1.38114754,  1.72213115, ..., -0.0057377 ,
        -0.0057377 , -0.00655738],
       [ 1.61803279, -0.61885246, -0.27786885, ..., -0.0057377 ,
        -0.0057377 , -0.00655738],
       [ 3.61803279, -0.61885246, -0.27786885, ..., -0.0057377 ,
        -0.0057377 , -0.00655738]])

In [60]:
user_centered = ratings.sub(user_means, axis = 0).to_numpy()

In [47]:
pearson_corr_item = cosine_similarity_movie(ratings_centered)
pearson_corr_item

array([[ 1.        ,  0.2313265 ,  0.1732128 , ..., -0.0289057 ,
        -0.0289057 , -0.0289057 ],
       [ 0.2313265 ,  1.        ,  0.19194487, ..., -0.01829073,
        -0.01829073, -0.01829073],
       [ 0.1732128 ,  0.19194487,  1.        , ..., -0.01172923,
        -0.01172923, -0.01172923],
       ...,
       [-0.0289057 , -0.01829073, -0.01172923, ...,  1.        ,
         1.        , -0.00164204],
       [-0.0289057 , -0.01829073, -0.01172923, ...,  1.        ,
         1.        , -0.00164204],
       [-0.0289057 , -0.01829073, -0.01172923, ..., -0.00164204,
        -0.00164204,  1.        ]])

In [67]:
import numpy as np
import ipytest

ipytest.autoconfig()

def similarity_matrix_diag_check(similarity_matrix):
    assert np.allclose(np.diag(similarity_matrix), 1.0) == True

def similarity_matrix_shape_check(sim_matrix, matrix):
    assert sim_matrix.shape == (matrix.shape[1], matrix.shape[1])

def user_similarity_matrix_shape_check(sim_matrix_user, ratings_arr):
    assert sim_matrix_user.shape == (ratings_arr.shape[0],ratings_arr.shape[0])

def correlation_matrix_allclose_check(similarity_matrix, ratings_arr, status):
    assert np.allclose(similarity_matrix, similarity_matrix.T) == True and np.allclose(np.corrcoef(ratings_arr, rowvar=status), similarity_matrix) == True

def test_similarity_matrix_item():
    global pearson_corr_item
    pearson_corr_item = cosine_similarity_movie(ratings_centered)
    similarity_matrix_diag_check(pearson_corr_item)
    similarity_matrix_shape_check(pearson_corr_item, ratings_centered)
    correlation_matrix_allclose_check(pearson_corr_item, ratings_arr, False)


def test_similarity_matrix_user():
    global pearson_corr_user
    pearson_corr_user = cosine_similarity_user(user_centered)
    similarity_matrix_diag_check(pearson_corr_user)
    user_similarity_matrix_shape_check(pearson_corr_user, user_centered)
    correlation_matrix_allclose_check(pearson_corr_user, ratings_arr, True)

ipytest.autoconfig(addopts=["--color=yes"])
ipytest.run("-v")

======================================= test session starts ========================================
platform darwin -- Python 3.12.2, pytest-7.4.4, pluggy-1.0.0 -- /opt/anaconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/hercules/projects/camellia
plugins: anyio-4.2.0, typeguard-4.3.0
collecting ... collected 2 items

t_6f092d9679344c1c8294cbecbbaf34db.py::test_similarity_matrix_item PASSED                    [ 50%]
t_6f092d9679344c1c8294cbecbbaf34db.py::test_similarity_matrix_user PASSED                    [100%]

======================================== 2 passed in 7.66s =========================================


<ExitCode.OK: 0>

In [64]:
print(pearson_corr_item)

[[ 1.          0.2313265   0.1732128  ... -0.0289057  -0.0289057
  -0.0289057 ]
 [ 0.2313265   1.          0.19194487 ... -0.01829073 -0.01829073
  -0.01829073]
 [ 0.1732128   0.19194487  1.         ... -0.01172923 -0.01172923
  -0.01172923]
 ...
 [-0.0289057  -0.01829073 -0.01172923 ...  1.          1.
  -0.00164204]
 [-0.0289057  -0.01829073 -0.01172923 ...  1.          1.
  -0.00164204]
 [-0.0289057  -0.01829073 -0.01172923 ... -0.00164204 -0.00164204
   1.        ]]


In [65]:
print(pearson_corr_user)

[[ 1.          0.01939982  0.05305554 ...  0.26224098  0.08543443
   0.09871925]
 [ 0.01939982  1.         -0.00259407 ...  0.03273037  0.024373
   0.08932854]
 [ 0.05305554 -0.00259407  1.         ...  0.00809613 -0.00296253
   0.01596195]
 ...
 [ 0.26224098  0.03273037  0.00809613 ...  1.          0.10956259
   0.24894421]
 [ 0.08543443  0.024373   -0.00296253 ...  0.10956259  1.
   0.03371258]
 [ 0.09871925  0.08932854  0.01596195 ...  0.24894421  0.03371258
   1.        ]]
